# CMake generated Testfile for 
# Source directory: /home/vagrant/artery/scenarios/storyboard
# Build directory: /home/vagrant/artery/Build_Collision/scenarios/storyboard
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[storyboard-inet]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Build_Collision/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Build_Collision/scenarios/highway-police/libartery_police.so" "-l" "/home/vagrant/artery/Build_Collision/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Build_Collision/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Build_Collision/extern/libINET.so" "-l" "/home/vagrant/artery/Build_Collision/extern/libveins.so" "-l" "/home/vagrant/artery/Build_Collision/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Build_Collision/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "--sim-time-limit=60s")
set_tests_properties([=[storyboard-inet]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/storyboard" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/storyboard/CMakeLists.txt;2;add_opp_test;/home/vagrant/artery/scenarios/storyboard/CMakeLists.txt;0;")
add_test([=[storyboard-veins]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Build_Collision/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Build_Collision/scenarios/highway-police/libartery_police.so" "-l" "/home/vagrant/artery/Build_Collision/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Build_Collision/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Build_Collision/extern/libINET.so" "-l" "/home/vagrant/artery/Build_Collision/extern/libveins.so" "-l" "/home/vagrant/artery/Build_Collision/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Build_Collision/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cveins" "--sim-time-limit=60s")
set_tests_properties([=[storyboard-veins]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/storyboard" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/storyboard/CMakeLists.txt;3;add_opp_test;/home/vagrant/artery/scenarios/storyboard/CMakeLists.txt;0;")
add_test([=[storyboard-repeat]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Build_Collision/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Build_Collision/scenarios/highway-police/libartery_police.so" "-l" "/home/vagrant/artery/Build_Collision/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Build_Collision/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Build_Collision/extern/libINET.so" "-l" "/home/vagrant/artery/Build_Collision/extern/libveins.so" "-l" "/home/vagrant/artery/Build_Collision/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Build_Collision/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-crepeat")
set_tests_properties([=[storyboard-repeat]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/storyboard" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/storyboard/CMakeLists.txt;4;add_opp_test;/home/vagrant/artery/scenarios/storyboard/CMakeLists.txt;0;")
