# CMake generated Testfile for 
# Source directory: /home/vagrant/artery/scenarios/rsu_grid
# Build directory: /home/vagrant/artery/build_ICSGTEIS/scenarios/rsu_grid
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[rsu_grid-omnidirectional]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/scenarios/highway-police/libartery_police.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/extern/libINET.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/extern/libveins.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/traci/libtraci.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-comnidirectional_test")
set_tests_properties([=[rsu_grid-omnidirectional]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/rsu_grid" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/rsu_grid/CMakeLists.txt;2;add_opp_test;/home/vagrant/artery/scenarios/rsu_grid/CMakeLists.txt;0;")
add_test([=[rsu_grid-directional]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/scenarios/highway-police/libartery_police.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/extern/libINET.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/extern/libveins.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/traci/libtraci.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cdirectional_test")
set_tests_properties([=[rsu_grid-directional]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/rsu_grid" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/rsu_grid/CMakeLists.txt;3;add_opp_test;/home/vagrant/artery/scenarios/rsu_grid/CMakeLists.txt;0;")
add_test([=[rsu_grid-rsu_sensors]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/scenarios/highway-police/libartery_police.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/extern/libINET.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/extern/libveins.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/traci/libtraci.so" "-l" "/home/vagrant/artery/build_ICSGTEIS/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-crsu_sensors_test")
set_tests_properties([=[rsu_grid-rsu_sensors]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/rsu_grid" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/rsu_grid/CMakeLists.txt;4;add_opp_test;/home/vagrant/artery/scenarios/rsu_grid/CMakeLists.txt;0;")
