[General]
network = artery.inet.World
sim-time-limit = 140s
debug-on-errors = true
print-undisposed = true

result-dir = results/
**.scalar-recording = false
**.vector-recording = false

*.traci.launcher.typename = "PosixLauncher"
# *.traci.launcher.sumocfg = "Pedestrian_walk.sumocfg" 
# *.traci.launcher.sumocfg = "New_Collision.sumocfg"
*.traci.launcher.sumocfg = "Extensive_Nodes.sumocfg"
*.traci.launcher.sumo = "sumo"
*.traci.ignorePersons = false
*.manager.traci.debug = true

*.traci.mapper.typename = "traci.MultiTypeModuleMapper"
*.traci.mapper.basicNodeManager = "traci.nodes"
*.traci.mapper.vehicleTypes = xml \
("\
    <vehicles vClass=\"passenger\"> \
        <vehicle type=\"artery.inet.Car\" rate=\"1.0\" /> \
        <vehicle type=\"artery.inet.PlainVehicle\" rate=\"0\" /> \
    </vehicles> \
")
*.traci.mapper.personTypes = xml \
("\
    <persons vClass=\"pedestrian\"> \
        <person type=\"artery.inet.Person\" rate=\"1.0\" /> \
        <person type=\"artery.inet.PlainPerson\" rate=\"0.0\" /> \
    </persons> \
")

*.node[*].middleware.services = xmldoc("services.xml")
*.node[*].middleware.updateInterval = 0.1s
*.node[*].middleware.datetime = "2004-01-01 00:00:00"
*.node[*].application.sendInterval = 0.1s
*.node[*].application.logInterval = 0.1s
*.node[*].middleware.TrajApp.staticSpeedThreshold = 0.5
*.node[*].application.debug = true
*.node[*].middleware.TrajApp.logFileName = "results/trajektori_log.csv"

*.node[*].wlan[*].typename = "VanetNic"
*.node[*].wlan[*].radio.channelNumber = 180
*.node[*].wlan[*].radio.carrierFrequency = 5.9GHz
*.node[*].wlan[*].radio.transmitter.power = 20mW
