# CMake generated Testfile for 
# Source directory: /home/vagrant/artery/scenarios/artery
# Build directory: /home/vagrant/artery/Intersection/scenarios/artery
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[example-inet]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Intersection/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Intersection/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Intersection/extern/libINET.so" "-l" "/home/vagrant/artery/Intersection/extern/libveins.so" "-l" "/home/vagrant/artery/Intersection/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Intersection/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cinet" "--sim-time-limit=20s")
set_tests_properties([=[example-inet]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/artery" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;2;add_opp_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;0;")
add_test([=[example-security]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Intersection/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Intersection/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Intersection/extern/libINET.so" "-l" "/home/vagrant/artery/Intersection/extern/libveins.so" "-l" "/home/vagrant/artery/Intersection/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Intersection/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cinet_security" "--sim-time-limit=20s")
set_tests_properties([=[example-security]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/artery" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;3;add_opp_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;0;")
add_test([=[example-inet-mco]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Intersection/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Intersection/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Intersection/extern/libINET.so" "-l" "/home/vagrant/artery/Intersection/extern/libveins.so" "-l" "/home/vagrant/artery/Intersection/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Intersection/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cinet_mco" "--sim-time-limit=20s")
set_tests_properties([=[example-inet-mco]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/artery" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;4;add_opp_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;0;")
add_test([=[example-inet-mixed-vehicles]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Intersection/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Intersection/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Intersection/extern/libINET.so" "-l" "/home/vagrant/artery/Intersection/extern/libveins.so" "-l" "/home/vagrant/artery/Intersection/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Intersection/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cinet_multiple_vehicle_types" "--sim-time-limit=20s")
set_tests_properties([=[example-inet-mixed-vehicles]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/artery" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;5;add_opp_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;0;")
add_test([=[example-inet-nakagami]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Intersection/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Intersection/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Intersection/extern/libINET.so" "-l" "/home/vagrant/artery/Intersection/extern/libveins.so" "-l" "/home/vagrant/artery/Intersection/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Intersection/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cinet_nakagami" "--sim-time-limit=20s")
set_tests_properties([=[example-inet-nakagami]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/artery" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;6;add_opp_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;0;")
add_test([=[example-inet-rsu]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Intersection/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Intersection/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Intersection/extern/libINET.so" "-l" "/home/vagrant/artery/Intersection/extern/libveins.so" "-l" "/home/vagrant/artery/Intersection/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Intersection/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cinet_rsu" "--sim-time-limit=20s")
set_tests_properties([=[example-inet-rsu]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/artery" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;7;add_opp_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;0;")
add_test([=[example-veins]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Intersection/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Intersection/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Intersection/extern/libINET.so" "-l" "/home/vagrant/artery/Intersection/extern/libveins.so" "-l" "/home/vagrant/artery/Intersection/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Intersection/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cveins" "--sim-time-limit=20s")
set_tests_properties([=[example-veins]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/artery" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;8;add_opp_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;0;")
add_test([=[example-veins-rsu]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Intersection/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Intersection/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Intersection/extern/libINET.so" "-l" "/home/vagrant/artery/Intersection/extern/libveins.so" "-l" "/home/vagrant/artery/Intersection/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Intersection/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cveins_rsu" "--sim-time-limit=20s")
set_tests_properties([=[example-veins-rsu]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/artery" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;9;add_opp_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;0;")
add_test([=[example-envmod]=] "/opt/omnetpp/bin/opp_run_dbg" "-n" "/home/vagrant/artery/src/artery:/home/vagrant/artery/src/traci:/home/vagrant/artery/extern/veins/examples/veins:/home/vagrant/artery/extern/veins/src/veins:/home/vagrant/artery/extern/inet/src:/home/vagrant/artery/extern/inet/examples:/home/vagrant/artery/extern/inet/tutorials:/home/vagrant/artery/extern/inet/showcases" "-l" "/home/vagrant/artery/Intersection/src/artery/envmod/libartery_envmod.so" "-l" "/home/vagrant/artery/Intersection/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/vagrant/artery/Intersection/extern/libINET.so" "-l" "/home/vagrant/artery/Intersection/extern/libveins.so" "-l" "/home/vagrant/artery/Intersection/src/traci/libtraci.so" "-l" "/home/vagrant/artery/Intersection/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cenvmod" "--sim-time-limit=20s")
set_tests_properties([=[example-envmod]=] PROPERTIES  WORKING_DIRECTORY "/home/vagrant/artery/scenarios/artery" _BACKTRACE_TRIPLES "/home/vagrant/artery/cmake/AddOppRun.cmake;170;add_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;12;add_opp_test;/home/vagrant/artery/scenarios/artery/CMakeLists.txt;0;")
